/**
 * Embeds /shared assets (system prompt + JSON Schemas) into a generated
 * TypeScript module so the gateway bundles to a single dependency-free file.
 * Checked-in output: gateway/src/generated.ts — regenerate with `npm run gen`
 * whenever /shared changes.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const shared = path.join(here, "..", "..", "shared");

const systemPrompt = readFileSync(path.join(shared, "prompts", "system.md"), "utf8");
const schema = (name) =>
  JSON.parse(readFileSync(path.join(shared, "schema", name), "utf8"));

const out = `// GENERATED by server/scripts/gen-assets.mjs from /shared — do not edit by hand.

/** shared/prompts/system.md, verbatim. */
export const SYSTEM_PROMPT: string = ${JSON.stringify(systemPrompt)};

/** shared/schema/*.json, keyed by $id basename. */
export const SCHEMAS: Record<string, object> = {
  "model-turn.schema.json": ${JSON.stringify(schema("model-turn.schema.json"))},
  "patch.schema.json": ${JSON.stringify(schema("patch.schema.json"))},
  "node.schema.json": ${JSON.stringify(schema("node.schema.json"))},
  "scenario.schema.json": ${JSON.stringify(schema("scenario.schema.json"))},
};
`;

writeFileSync(path.join(here, "..", "gateway", "src", "generated.ts"), out);
console.log("wrote gateway/src/generated.ts");
